import "package:flutter/material.dart";

class ColorsTheme {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color.fromRGBO(80, 36, 35, 1),
      // primary: Color(0xffa50015),
      surfaceTint: Color.fromRGBO(80, 36, 35, 1),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color.fromRGBO(80, 36, 35, 1),
      // primaryContainer: Color(0xffea0022),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xffb42728),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffff726a),
      onSecondaryContainer: Color(0xff2e0002),
      tertiary: Color(0xff794200),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffdedede),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xffffffff),
      onSurface: Color(0xff4a4a4a),
      onSurfaceVariant: Color(0xff5a5a5a),
      outline: Color(0xff9b9b9b),
      outlineVariant: Color(0xfffdfdfd),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff412b29),
      inversePrimary: Color(0xffffb3ad),
      primaryFixed: Color(0xfffdfdfd),
      onPrimaryFixed: Color(0xff410003),
      primaryFixedDim: Color(0xffffb3ad),
      onPrimaryFixedVariant: Color(0xff930011),
      secondaryFixed: Color(0xffffffff),
      onSecondaryFixed: Color(0xff410003),
      secondaryFixedDim: Color(0xffffb3ad),
      onSecondaryFixedVariant: Color(0xff910814),
      tertiaryFixed: Color(0xffffffff),
      onTertiaryFixed: Color(0xff2e1500),
      tertiaryFixedDim: Color(0xffffb778),
      onTertiaryFixedVariant: Color(0xff8a8a8a),
      surfaceDim: Color(0xffffffff),
      surfaceBright: Color(0xffffffff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xffffffff),
      surfaceContainer: Color(0xffffffff),
      surfaceContainerHigh: Color(0xffffffff),
      surfaceContainerHighest: Color(0xffffffff),
    );
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff8b0010),
      surfaceTint: Color(0xffc0001a),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color.fromRGBO(80, 36, 35, 1),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff8b0110),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color.fromRGBO(98, 44, 43, 1),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff663700),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffae6100),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff8c0009),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffda342e),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff8f7),
      onSurface: Color(0xff2a1615),
      onSurfaceVariant: Color(0xff5a3b38),
      outline: Color(0xff7a5653),
      outlineVariant: Color(0xff98716e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff412b29),
      inversePrimary: Color(0xffffb3ad),
      primaryFixed: Color(0xffea0022),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xffbb0019),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xffd33e3b),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xffb02426),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xffae6100),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff8a4c00),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xfff6d2ce),
      surfaceBright: Color(0xfffff8f7),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff0ef),
      surfaceContainer: Color(0xffffe9e7),
      surfaceContainerHigh: Color(0xffffe2df),
      surfaceContainerHighest: Color(0xffffdad6),
    );
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff4d0005),
      surfaceTint: Color(0xffc0001a),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff8b0010),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff4d0005),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff8b0110),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff371b00),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff663700),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff4e0002),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff8c0009),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff8f7),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff371c1a),
      outline: Color(0xff5a3b38),
      outlineVariant: Color(0xff5a3b38),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff412b29),
      inversePrimary: Color(0xffffe7e4),
      primaryFixed: Color(0xff8b0010),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff610008),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff8b0110),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff610008),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff663700),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff462400),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xfff6d2ce),
      surfaceBright: Color(0xfffff8f7),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff0ef),
      surfaceContainer: Color(0xffffe9e7),
      surfaceContainerHigh: Color(0xffffe2df),
      surfaceContainerHighest: Color(0xffffdad6),
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb3ad),
      surfaceTint: Color(0xffffb3ad),
      onPrimary: Color(0xff680009),
      primaryContainer: Color(0xffea0022),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xffffb3ad),
      onSecondary: Color(0xff680009),
      secondaryContainer: Color(0xff86000f),
      onSecondaryContainer: Color(0xffffc8c3),
      tertiary: Color(0xffffb778),
      onTertiary: Color(0xff4c2700),
      tertiaryContainer: Color(0xffae6100),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff210e0d),
      onSurface: Color(0xffffdad6),
      onSurfaceVariant: Color(0xffe9bcb7),
      outline: Color(0xffb08783),
      outlineVariant: Color(0xff5f3e3c),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffffdad6),
      inversePrimary: Color(0xffc0001a),
      primaryFixed: Color(0xffffdad6),
      onPrimaryFixed: Color(0xff410003),
      primaryFixedDim: Color(0xffffb3ad),
      onPrimaryFixedVariant: Color(0xff930011),
      secondaryFixed: Color(0xffffdad6),
      onSecondaryFixed: Color(0xff410003),
      secondaryFixedDim: Color(0xffffb3ad),
      onSecondaryFixedVariant: Color(0xff910814),
      tertiaryFixed: Color(0xffffdcc1),
      onTertiaryFixed: Color(0xff2e1500),
      tertiaryFixedDim: Color(0xffffb778),
      onTertiaryFixedVariant: Color(0xff6c3a00),
      surfaceDim: Color(0xff210e0d),
      surfaceBright: Color(0xff4b3331),
      surfaceContainerLowest: Color(0xff1b0908),
      surfaceContainerLow: Color(0xff2a1615),
      surfaceContainer: Color(0xff2f1a18),
      surfaceContainerHigh: Color(0xff3a2422),
      surfaceContainerHighest: Color(0xff462f2d),
    );
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb9b3),
      surfaceTint: Color(0xffffb3ad),
      onPrimary: Color(0xff370002),
      primaryContainer: Color(0xffff544f),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffffb9b3),
      onSecondary: Color(0xff370002),
      secondaryContainer: Color(0xfff95a54),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffffbd84),
      onTertiary: Color(0xff261100),
      tertiaryContainer: Color(0xffd37b18),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffbab1),
      onError: Color(0xff370001),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff210e0d),
      onSurface: Color(0xfffff9f9),
      onSurfaceVariant: Color(0xffeec0bc),
      outline: Color(0xffc39995),
      outlineVariant: Color(0xffa17a76),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffffdad6),
      inversePrimary: Color(0xff950012),
      primaryFixed: Color(0xffffdad6),
      onPrimaryFixed: Color(0xff2d0002),
      primaryFixedDim: Color(0xffffb3ad),
      onPrimaryFixedVariant: Color(0xff73000b),
      secondaryFixed: Color(0xffffdad6),
      onSecondaryFixed: Color(0xff2d0002),
      secondaryFixedDim: Color(0xffffb3ad),
      onSecondaryFixedVariant: Color(0xff73000b),
      tertiaryFixed: Color(0xffffdcc1),
      onTertiaryFixed: Color(0xff1f0d00),
      tertiaryFixedDim: Color(0xffffb778),
      onTertiaryFixedVariant: Color(0xff542c00),
      surfaceDim: Color(0xff210e0d),
      surfaceBright: Color(0xff4b3331),
      surfaceContainerLowest: Color(0xff1b0908),
      surfaceContainerLow: Color(0xff2a1615),
      surfaceContainer: Color(0xff2f1a18),
      surfaceContainerHigh: Color(0xff3a2422),
      surfaceContainerHighest: Color(0xff462f2d),
    );
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xfffff9f9),
      surfaceTint: Color(0xffffb3ad),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffffb9b3),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xfffff9f9),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffffb9b3),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xfffffaf8),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffffbd84),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xfffff9f9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffbab1),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff210e0d),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xfffff9f9),
      outline: Color(0xffeec0bc),
      outlineVariant: Color(0xffeec0bc),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffffdad6),
      inversePrimary: Color(0xff5c0007),
      primaryFixed: Color(0xffffe0dd),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffffb9b3),
      onPrimaryFixedVariant: Color(0xff370002),
      secondaryFixed: Color(0xffffe0dd),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffffb9b3),
      onSecondaryFixedVariant: Color(0xff370002),
      tertiaryFixed: Color(0xffffe1cb),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffffbd84),
      onTertiaryFixedVariant: Color(0xff261100),
      surfaceDim: Color(0xff210e0d),
      surfaceBright: Color(0xff4b3331),
      surfaceContainerLowest: Color(0xff1b0908),
      surfaceContainerLow: Color(0xff2a1615),
      surfaceContainer: Color(0xff2f1a18),
      surfaceContainerHigh: Color(0xff3a2422),
      surfaceContainerHighest: Color(0xff462f2d),
    );
  }
}
